- Makefile
- terraform/groups/ecs-service/locals.tf
- terraform/groups/ecs-service/variables.tf
* Added chs_kafka_api_url to list of service secrets
* Defined healthcheck and loadbalancer paths as Billy advised
* Changed stack name to reference correct public stack
* Removed reference to routes.yml in makefile
[DSND-2302](https://companieshouse.atlassian.net/browse/DSND-2302)
- [Y] Is the PR as small as it can be?
- [Y] Has the Jira ticket been updated with any relevant comments?
- [Y] Is the `README` up to date?
- [y] Has the `POM` been updated for the latest versions of dependencies?
- [y] Has the code been double-checked against `main`?
- [y] Does the code adhere standards in this repository, including SonarQube checks?
- [N/A] Do the code changes have unit and integration tests with code coverage > 80%?
- [N/A] Has the code been tested locally and/or passed the API Karate tests …
> DSND-2302: Correct terraform config

- Makefile
- start.sh
> DSND-2118: Add start script

- pom.xml
- suppress.xml
- terraform/groups/ecs-service/locals.tf
- terraform/groups/ecs-service/variables.tf
[DSND-2118](https://companieshouse.atlassian.net/browse/DSND-2118)
[DSND-2118]: https://companieshouse.atlassian.net/browse/DSND-2118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2118: Update pom.xml and remove unnecessary terraform

- terraform/groups/ecs-service/locals.tf
[DSND-2118](https://companieshouse.atlassian.net/browse/DSND-2118)
[DSND-2118]: https://companieshouse.atlassian.net/browse/DSND-2118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2118: Remove duplicate secret already in vault

- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/filinghistory/api/FilingHistoryApplicationIT.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/interceptor/AuthenticationInterceptorITest.java
- terraform/groups/ecs-service/data.tf
- terraform/groups/ecs-service/locals.tf
[DSND-2118](https://companieshouse.atlassian.net/browse/DSND-2118)
[DSND-2118]: https://companieshouse.atlassian.net/browse/DSND-2118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2118: Change LB and prefix healthcheck

- terraform/groups/ecs-service/locals.tf
[DSND-2118](https://companieshouse.atlassian.net/browse/DSND-2118)
[DSND-2118]: https://companieshouse.atlassian.net/browse/DSND-2118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2118: Change lb rule priority

- pom.xml
Moved the dependencies to be exclusions rather than specific imports
Related Jira tickets
[DSND-2385](https://companieshouse.atlassian.net/browse/DSND-2385)
[DSND-2385]: https://companieshouse.atlassian.net/browse/DSND-2385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2385: POM updates and exclusions

- src/main/resources/application.properties
* Changes the value of the mongo DB URI as it will be taken from vault instead
[DSND-2170](https://companieshouse.atlassian.net/browse/DSND-2170)
[DSND-2170]: https://companieshouse.atlassian.net/browse/DSND-2170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2170: Update mongo uri value; will be taken from vault

- terraform/groups/ecs-service/data.tf
- terraform/groups/ecs-service/main.tf
* This change is required so that the internal endpoints can be hit through the private LB which does not have rate limiting applied to it.
[DSND-2170](https://companieshouse.atlassian.net/browse/DSND-2170)
[DSND-2170]: https://companieshouse.atlassian.net/browse/DSND-2170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2170: Add terraform config for private API load-balancer

- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
> use env files true

- pom.xml
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/get/ItemGetResponseMapper.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/DataMapper.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/model/FilingHistoryData.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryControllerIT.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryControllerMongoUnavailableIT.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/logging/RequestLoggingFilterIT.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/mapper/get/ItemGetResponseMapperTest.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/DataMapperTest.java
- src/test/resources/filing-history-document-list-subcategory.json
* Subcategory can be a single string or a list of strings.
* Returns 400 bad request when neither.
[DSND-2406](https://companieshouse.atlassian.net/browse/DSND-2406)
[DSND-2406]: https://companieshouse.atlassian.net/browse/DSND-2406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2406: Handle dynamic subcategory type

- terraform/groups/ecs-service/main.tf
- terraform/groups/ecs-service/variables.tf
> deploy service with multiple lb fix

- README.md
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/get/LinksGetResponseMapper.java
- src/main/resources/application.properties
* Make API key env var consistent with name on Mongo document
* Make port configurable
[DSND-2318](https://companieshouse.atlassian.net/browse/DSND-2318)
[DSND-2318]: https://companieshouse.atlassian.net/browse/DSND-2318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2318: Make API key name consistent with Mongo

- terraform/groups/ecs-service/main.tf
> bump to fix  hyphen truncate

- terraform/groups/ecs-service/locals.tf
[DSND-2167](https://companieshouse.atlassian.net/browse/DSND-2167)
[DSND-2167]: https://companieshouse.atlassian.net/browse/DSND-2167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2167: Fix loadbalancer path so delete will go through

- src/main/java/uk/gov/companieshouse/filinghistory/api/repository/Repository.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryControllerMongoUnavailableIT.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryControllerTest.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/repository/RepositoryTest.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryGetResponseProcessorTest.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryServiceTest.java
* Change respective Service, Processor, Controller to throw and catch ServiceUnavailable
* Add missing get single transaction unit tests
[DSND-2422](https://companieshouse.atlassian.net/browse/DSND-2422)
Cant be tested on any environments besides local Tilt.
[DSND-2422]: https://companieshouse.atlassian.net/browse/DSND-2422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2422 Change findCompanyFilingHistory to catch DataAccessException

- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/ResolutionTransactionIT.java
- src/test/resources/mongo_docs/resolutions/existing_resolution_doc.json
- src/test/resources/mongo_docs/resolutions/expected_resolution_doc_no_barcode.json
- src/test/resources/put_requests/resolutions/put_request_body_resolution_no_barcode.json
Just an additional Itest for resolutions without a barcode. Locally tested.
[DSND-2363](https://companieshouse.atlassian.net/browse/DSND-2363)
[DSND-2363]: https://companieshouse.atlassian.net/browse/DSND-2363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2363: Composite resolution without barcode additional test

- pom.xml
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/AbstractTransactionMapper.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/AnnotationTransactionMapper.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/AssociatedFilingTransactionMapper.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/ResolutionTransactionMapper.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/model/mongo/FilingHistoryDocument.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/AnnotationTransactionIT.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/AnnotationTransactionMapperTest.java
- src/test/resources/mongo_docs/annotations/existing_top_level_annotation_doc.json
- src/test/resources/mongo_docs/annotations/expected_top_level_annotation_doc.json
- src/test/resources/mongo_docs/annotations/expected_top_level_annotation_doc_with_child_annotation.json
- src/test/resources/put_requests/annotation/put_request_body_top_level_annotation.json
* Top level annotations are persisted using the entity_id whereas child annotations use the parent_entity_id.
* Top level annotations also have more top and data level fields set compared to child annotations.
[DSND-2371](https://companieshouse.atlassian.net/browse/DSND-2371)
[DSND-2371]: https://companieshouse.atlassian.net/browse/DSND-2371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2371: Implement handling of top level annotations

- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/TopLevelTransactionMapper.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryControllerIT.java
- src/test/resources/mongo_docs/newinc/existing_new_inc_with_SH01_and_MODEL_ARTICLES_doc.json
- src/test/resources/mongo_docs/newinc/existing_new_inc_with_SH01_doc.json
- src/test/resources/mongo_docs/newinc/expected_new_inc_with_SH01_and_MODEL_ARTICLES_doc.json
- src/test/resources/mongo_docs/newinc/expected_new_inc_with_SH01_doc.json
- src/test/resources/put_requests/newinc/put_request_body_new_inc_with_SH01.json
*  Implement handling of NEWINC with embedded SH01 associated filing.
[DSND-2369](https://companieshouse.atlassian.net/browse/DSND-2369)
[DSND-2369]: https://companieshouse.atlassian.net/browse/DSND-2369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2369: Implement handling of NEWINC with embedded SH01

- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/AnnotationTransactionMapper.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/AnnotationTransactionIT.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/AnnotationTransactionMapperTest.java
- src/test/resources/mongo_docs/annotations/expected_top_level_annotation_doc.json
- src/test/resources/put_requests/annotation/put_request_body_top_level_annotation.json
* When a top level annotation is updated both the data level fields
and child level fields should be updated.
[DSND-2371](https://companieshouse.atlassian.net/browse/DSND-2371)
[DSND-2371]: https://companieshouse.atlassian.net/browse/DSND-2371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2371: Fix updating of top level annotations

- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/ResolutionTransactionMapper.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/ResolutionTransactionIT.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/AnnotationTransactionMapperTest.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/ResolutionTransactionMapperTest.java
- src/test/resources/mongo_docs/resolutions/existing_certnm_doc.json
- src/test/resources/mongo_docs/resolutions/existing_certnm_doc_with_legacy_res15.json
- src/test/resources/mongo_docs/resolutions/existing_certnm_doc_with_nm01.json
- src/test/resources/mongo_docs/resolutions/existing_certnm_doc_with_res15.json
- src/test/resources/mongo_docs/resolutions/existing_res15_doc_with_no_parent.json
- src/test/resources/mongo_docs/resolutions/expected_certnm_doc_with_nm01_and_res15.json
- src/test/resources/mongo_docs/resolutions/expected_certnm_doc_with_res15.json
- src/test/resources/mongo_docs/resolutions/expected_certnm_doc_with_two_res15s.json
- src/test/resources/mongo_docs/resolutions/expected_res15_doc_with_no_parent.json
- src/test/resources/put_requests/certnms/put_request_body_certnm.json
- src/test/resources/put_requests/resolutions/put_request_body_res15.json
* PUT requests sent to the API with a parent entity ID and transaction kind of "resolution" are handled differently than composite resolutions.
[DSND-2561](https://companieshouse.atlassian.net/browse/DSND-2561)
[DSND-2561]: https://companieshouse.atlassian.net/browse/DSND-2561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2561: Implement handling of child resolutions

- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/DateUtils.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/AbstractTransactionMapper.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/AnnotationTransactionMapper.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/AssociatedFilingTransactionMapper.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/ChildListMapper.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/ResolutionTransactionMapper.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/TopLevelTransactionMapper.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryUpsertProcessor.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/AnnotationTransactionMapperTest.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/AssociatedFilingTransactionMapperTest.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/ResolutionTransactionMapperTest.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/TopLevelTransactionMapperTest.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryUpsertProcessorTest.java
* Tests use the the public methods not the implementations of the abstract methods.
* Changed order of top level mapping and data mapping.
* Moved update existing transaction method to abstract class.
[DSND-2561](https://companieshouse.atlassian.net/browse/DSND-2561)
[DSND-2561]: https://companieshouse.atlassian.net/browse/DSND-2561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2561: Further refactoring of upsert transaction mappers

- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryControllerIT.java
* Wrote integration tests for insert but realised they were already covered.
* Delete tests written.
* Locally tested to be sure insert and delete functionality works as expected.
[DSND-2384](https://companieshouse.atlassian.net/browse/DSND-2384)
[DSND-2384]: https://companieshouse.atlassian.net/browse/DSND-2384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2384: Write NEWINC delete integration tests.

- src/main/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryController.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/service/DeleteProcessor.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryControllerTest.java
[DSND-2326](https://companieshouse.atlassian.net/browse/DSND-2326)
[DSND-2326]: https://companieshouse.atlassian.net/browse/DSND-2326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2326: Rename path variable for delete endpoint

- src/main/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryController.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/AnnotationTransactionIT.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/AssociatedFilingTransactionIT.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryControllerIT.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryControllerMongoUnavailableIT.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/ResolutionTransactionIT.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/logging/RequestLoggingFilterIT.java
- terraform/groups/ecs-service/locals.tf
* Remove service prefix from LB paths and endpoints
[DSND-2692](https://companieshouse.atlassian.net/browse/DSND-2692)
[DSND-2692]: https://companieshouse.atlassian.net/browse/DSND-2692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2692: Remove service prefix from LB paths and endpoints

- terraform/groups/ecs-service/main.tf
> Add back public lb since path changes

- terraform/groups/ecs-service/main.tf
Reverts companieshouse/filing-history-data-api#62
> Revert "Add back public lb since path changes" for live deployments

- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/delete/DeleteMapperDelegatorAspect.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/mapper/delete/DeleteMapperDelegatorAspectFeatureDisabledIT.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/mapper/delete/DeleteMapperDelegatorAspectTest.java
* Allows NEWINCs with SH01 children to be deleted when the feature is disabled.
* Needs tested locally.
[DSND-2715](https://companieshouse.atlassian.net/browse/DSND-2715)
[DSND-2715]: https://companieshouse.atlassian.net/browse/DSND-2715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2715: Refactor child deletion feature flag

- terraform/groups/ecs-service/main.tf
[DSND-2794](https://companieshouse.atlassian.net/browse/DSND-2794)
[DSND-2794]: https://companieshouse.atlassian.net/browse/DSND-2794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2794: Add back public LB for live release

- terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/phoenix1/vars
> Add phoenix1 instance of filing history data api

- .gitignore
- Tiltfile.dev
- pom.xml
- src/main/java/uk/gov/companieshouse/filinghistory/api/config/WebSecurityConfig.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryControllerCORSTest.java
filing-history-data-api CORS
SEC-51 
> SEC-51 filing-history-data-api CORS

- pom.xml
> Up parent pom version to fix failing security pipeline job

- pom.xml
- src/main/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryController.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/AbstractTransactionMapper.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/ResourceChangedRequestMapper.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/model/ResourceChangedRequest.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryService.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryUpsertProcessor.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/service/Service.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/service/UpsertProcessor.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryControllerTest.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/DataMapperTest.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/ResourceChangedRequestMapperTest.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/TopLevelTransactionMapperTest.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryServiceTest.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryUpsertProcessorTest.java
Add document metadata patch endpoint
> Doc metadata patch

- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
[DSND-2833](https://companieshouse.atlassian.net/browse/DSND-2833)
[DSND-2833]: https://companieshouse.atlassian.net/browse/DSND-2833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2833: Increase desired tasks, cpus and memory

- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
> DSND-2833: Bump CPU and memory

- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
[DSND-2906](https://companieshouse.atlassian.net/browse/DSND-2906)
[DSND-2906]: https://companieshouse.atlassian.net/browse/DSND-2906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2906: Increase minimum task count to 3 in live

- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
- terraform/groups/ecs-service/variables.tf
[DSND-2906](https://companieshouse.atlassian.net/browse/DSND-2906)
[DSND-2906]: https://companieshouse.atlassian.net/browse/DSND-2906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2906: Add min task count variable

- terraform/groups/ecs-service/main.tf
[DSND-2906](https://companieshouse.atlassian.net/browse/DSND-2906)
[DSND-2906]: https://companieshouse.atlassian.net/browse/DSND-2906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2906: Add min task count to main.tf

- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
[DSND-2906](https://companieshouse.atlassian.net/browse/DSND-2906)
[DSND-2906]: https://companieshouse.atlassian.net/browse/DSND-2906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2906: Up min tasks to 8 in live

- src/main/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryService.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryControllerIT.java
[DSND-2965](https://companieshouse.atlassian.net/browse/DSND-2965)
[DSND-2965]: https://companieshouse.atlassian.net/browse/DSND-2965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2965: Fix compensatory transactions for legacy documents

- pom.xml
- src/main/java/uk/gov/companieshouse/filinghistory/api/auth/AuthenticationInterceptor.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/client/ResourceChangedApiClientAspect.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryController.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/logging/RequestLoggingFilter.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/delete/DeleteMapperDelegator.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/delete/DeleteMapperDelegatorAspect.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/AbstractTransactionMapperFactory.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/upsert/ChildListMapper.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/repository/Repository.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryDeleteProcessor.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryGetResponseProcessor.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryService.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryUpsertProcessor.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/service/ValidatorFactory.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/repository/RepositoryIT.java
This PR primarily adds entity id to the log map at the PUT/DELETE requests in the controller so this field can be tracked more easily, by FESS, back to CHIPS.
Other changes also made to simplify log messages.
[DSND-2872](https://companieshouse.atlassian.net/browse/DSND-2872)
[DSND-2872]: https://companieshouse.atlassian.net/browse/DSND-2872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2872: Update structured logging

- src/main/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryUpsertProcessor.java
* added document metadata link to the logmap - includes an encoded document id.
[DSND-3086](https://companieshouse.atlassian.net/browse/DSND-3086)
[DSND-3086]: https://companieshouse.atlassian.net/browse/DSND-3086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-3086: Add document metadata to logmap

- pom.xml
* Revert certain dependencies to previously working versions for Concourse build-test-analyse job.
[DSND-3112](https://companieshouse.atlassian.net/browse/DSND-3112)
[DSND-3112]: https://companieshouse.atlassian.net/browse/DSND-3112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-3112: Revert certain dependencies in pom

- pom.xml
* Update pom so build-test-analyse job passes
[DSND-3112](https://companieshouse.atlassian.net/browse/DSND-3112)
[DSND-3112]: https://companieshouse.atlassian.net/browse/DSND-3112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-3112: Revert spring boot back to 3.3.4

- terraform/groups/ecs-service/profiles/development-eu-west-2/rebel1/vars
> Add rebel1 profile

- pom.xml
- src/main/java/uk/gov/companieshouse/filinghistory/api/mapper/DateUtils.java
* Upgrade internal dependency versions
* Upgrade jib maven plugin and spring versions
* Add transitive dependencies for logback classic and core
[BI-14123](https://companieshouse.atlassian.net/browse/BI-14123) 
[BI-14123]: https://companieshouse.atlassian.net/browse/BI-14123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-14123: Set published at format to use 24hr time

- Makefile
- pom.xml
- src/main/java/uk/gov/companieshouse/filinghistory/api/config/WebSecurityConfig.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/filinghistory/api/FilingHistoryApplicationIT.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/auth/AuthenticationInterceptorIT.java
- suppress.xml
- terraform/groups/ecs-service/locals.tf
[DSND-3241](https://companieshouse.atlassian.net/browse/DSND-3241)
[DSND-3241]: https://companieshouse.atlassian.net/browse/DSND-3241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-3241: Remove public healthcheck

- terraform/groups/ecs-service/locals.tf
Lowered rule priority to prevent clash with another service.
> Update rule priority

- pom.xml
- src/main/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryController.java
- src/main/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryGetResponseProcessor.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/controller/FilingHistoryControllerTest.java
- src/test/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryGetResponseProcessorTest.java
* When get list called with items_per_page=0
[DSND-3267](https://companieshouse.atlassian.net/browse/DSND-3267)
[DSND-3267]: https://companieshouse.atlassian.net/browse/DSND-3267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-3267: Set items per page to default when 0 provided

- pom.xml
Update Pom to add config for latest Sonar version on the pipeline
https://companieshouse.atlassian.net/browse/ASM-531
> ASM-531 Update Pom for latest Sonar

- docs/pull_request_template.md
> removed references to tilt
